import test from 'node:test';import assert from 'node:assert/strict';
import {capability,originOkay,randomToken,sha256,verifyCapability} from '../src/security.js';
import {magic,rangeSpec,route} from '../src/worker.js';
test('random session material is high entropy',()=>assert.ok(randomToken().length>=43));
test('hash is stable and not plaintext',async()=>{assert.equal(await sha256('x'),await sha256('x'));assert.notEqual(await sha256('x'),'x')});
test('capability accepts valid token',async()=>{const t=await capability('secret','opaque',60);assert.equal(await verifyCapability('secret','opaque',t),true)});
test('capability rejects tamper',async()=>{const t=await capability('secret','opaque',60);assert.equal(await verifyCapability('secret','other',t),false)});
test('capability rejects expiry',async()=>{const t=await capability('secret','opaque',-1);assert.equal(await verifyCapability('secret','opaque',t),false)});
test('origin exact match',()=>assert.equal(originOkay(new Request('https://x',{headers:{origin:'https://contest.example'}}),'https://contest.example'),true));
test('origin absent rejected',()=>assert.equal(originOkay(new Request('https://x'),'https://contest.example'),false));
test('range full absent',()=>assert.equal(rangeSpec(null,100),null));
test('range start end',()=>assert.deepEqual(rangeSpec('bytes=2-9',100),{offset:2,length:8,end:9}));
test('range open end',()=>assert.deepEqual(rangeSpec('bytes=90-',100),{offset:90,length:10,end:99}));
test('range suffix',()=>assert.deepEqual(rangeSpec('bytes=-10',100),{offset:90,length:10,end:99}));
test('range caps end',()=>assert.deepEqual(rangeSpec('bytes=90-999',100),{offset:90,length:10,end:99}));
test('range rejects multipart',()=>assert.equal(rangeSpec('bytes=1-2,4-5',100),false));
test('range rejects inverted',()=>assert.equal(rangeSpec('bytes=9-2',100),false));
test('range rejects beyond',()=>assert.equal(rangeSpec('bytes=100-',100),false));
test('mp3 ID3 magic',()=>assert.equal(magic(Uint8Array.from([0x49,0x44,0x33]),'mp3'),true));
test('mp3 frame magic',()=>assert.equal(magic(Uint8Array.from([0xff,0xfb]),'mp3'),true));
test('wav magic',()=>assert.equal(magic(new TextEncoder().encode('RIFF1234'),'wav'),true));
test('ogg magic',()=>assert.equal(magic(new TextEncoder().encode('OggS1234'),'ogg'),true));
test('extension mismatch rejected',()=>assert.equal(magic(new TextEncoder().encode('RIFF1234'),'mp3'),false));
test('robots protects private flows',async()=>{const r=await route(new Request('https://contest.example/robots.txt'),{});const s=await r.text();assert.match(s,/Disallow: \/api\//);assert.match(s,/Allow: \/works/)});
test('asset fallback delegates',async()=>{const env={ASSETS:{fetch:r=>new Response(new URL(r.url).pathname)}};assert.equal(await (await route(new Request('https://x/styles.css'),env)).text(),'/styles.css')});
test('missing mandatory configuration fails closed without binding names',async()=>{const env={DB:{prepare(){throw new Error('must not query')}}};const r=await route(new Request('https://x/api/public/competition?contest=guyun'),env);assert.equal(r.status,503);assert.deepEqual(await r.json(),{error:'service_not_configured'})});
