import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdtemp,readFile,readdir,rm,stat} from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
import os from 'node:os';
import path from 'node:path';
import worker from '../src/worker.js';
class Statement{constructor(db,sql){this.db=db;this.sql=sql;this.args=[]}bind(...a){this.args=a;return this}first(){return this.db.first(this.sql,this.args)}run(){return this.db.run(this.sql,this.args)}all(){return this.db.all(this.sql,this.args)}}
class MemoryD1{constructor(){this.counts=new Map();this.public=[{public_id:'legacy-005',sort_order:5}];this.audio={audio_object_key:'published/a.mp3',audio_content_type:'audio/mpeg',audio_size:6,audio_sha256:'a'.repeat(64)}}prepare(sql){return new Statement(this,sql)}async run(sql,args){if(sql.startsWith('INSERT INTO rate_limits')){const k=args.slice(0,3).join('|');this.counts.set(k,(this.counts.get(k)||0)+1)}return {meta:{changes:1}}}async first(sql,args){if(sql.includes('SELECT count FROM rate_limits'))return {count:this.counts.get(args.join('|'))||1};if(sql.includes("key='cost_circuit'"))return {value_json:'{"open":false}'};if(sql.includes("key='contest'"))return {value_json:'{"submission":{"startAt":null,"endAt":null},"voting":{"startAt":null,"endAt":null}}'};if(sql.includes('COUNT(*) distinct_ids'))return {distinct_ids:1,bytes:6};if(sql.includes('COUNT(DISTINCT public_id)'))return {distinct_ids:1,bytes:6};if(sql.includes('UNION ALL SELECT audio_object_key'))return this.audio;if(sql.includes('FROM vote_stages WHERE active=1'))return null;if(sql.includes('FROM sessions'))return null;return null}async all(sql){if(sql.includes('sort_order FROM'))return {results:this.public};return {results:[]}}}
const env=()=>({
  CANONICAL_ORIGIN:'https://contest.example',CAPABILITY_SECRET:'capability-test-secret',DB:new MemoryD1(),
  AUDIO:{async get(key,opt){const all=new TextEncoder().encode('abcdef'),range=opt?.range,bytes=range?all.slice(range.offset,range.offset+range.length):all;return {body:bytes,arrayBuffer:async()=>bytes.buffer};}},
  ASSETS:{fetch:r=>{const p=new URL(r.url).pathname;return new Response(`asset:${p}`,{headers:{'content-type':p==='/'||p.endsWith('.html')?'text/html; charset=utf-8':'text/plain'}})}}
});
const call=(url,init={},e=env())=>worker.fetch(new Request(`https://contest.example${url}`,{...init,headers:{'CF-Connecting-IP':'203.0.113.9',...(init.headers||{})}}),e,{});
test('actual Worker public competition succeeds without Discord Access or Turnstile config',async()=>{const e=env(),r=await call('/api/public/competition?contest=guyun',{},e);assert.equal(r.status,200);const j=await r.json();assert.equal(j.works.length,1);assert.deepEqual(Object.keys(j.works[0]),['publicId','listenUrl']);assert.match(j.works[0].listenUrl,/token=/);assert.equal(r.headers.get('x-content-type-options'),'nosniff')});
test('actual Worker audio supports GET HEAD range 416 ETag and publication lookup',async()=>{const e=env(),listing=await (await call('/api/public/competition?contest=guyun',{},e)).json(),url=listing.works[0].listenUrl;let r=await call(url,{headers:{range:'bytes=1-3'}},e);assert.equal(r.status,206);assert.equal(await r.text(),'bcd');assert.equal(r.headers.get('content-range'),'bytes 1-3/6');r=await call(url,{method:'HEAD'},e);assert.equal(r.status,200);assert.equal(await r.text(),'');r=await call(url,{headers:{range:'bytes=9-'}},e);assert.equal(r.status,416);r=await call(url,{headers:{'if-none-match':`"${'a'.repeat(64)}"`}},e);assert.equal(r.status,304)});
test('legacy direct static media is denied before ASSETS',async()=>{const r=await call('/media/submissions/a.mp3');assert.equal(r.status,404);assert.deepEqual(await r.json(),{error:'not_found'})});
test('all protected endpoint families fail closed without session or Access',async()=>{for(const [method,url,body]of [['GET','/api/me/registration'],['POST','/api/registration',new FormData()],['PUT','/api/registration/1',new FormData()],['GET','/api/me/vote'],['PUT','/api/me/vote','{}'],['POST','/auth/logout'],['GET','/admin'],['GET','/api/admin/overview'],['GET','/api/admin/registrations'],['PUT','/api/admin/registrations/1','{}'],['GET','/api/admin/votes'],['GET','/api/admin/audit'],['GET','/api/admin/export'],['GET','/api/admin/settings'],['PUT','/api/admin/settings','{}'],['GET','/api/admin/schedule'],['PUT','/api/admin/schedule','{}']]){const r=await call(url,{method,body:method==='GET'?undefined:body});assert.ok([401,503].includes(r.status),`${method} ${url}: ${r.status}`)}});
test('public voting and owned pages have matching contracts',async()=>{assert.deepEqual(await (await call('/api/public/voting')).json(),{stage:null});for(const p of ['/works','/vote']){const r=await call(p);assert.equal(r.status,200);assert.match(r.headers.get('content-type'),/text\/html/)}const e=env();let assetPath='';e.ASSETS={fetch:r=>{assetPath=new URL(r.url).pathname;return new Response('<html></html>',{headers:{'content-type':'text/html'}})}};const works=await call('/works',{},e);assert.equal(works.status,200);assert.equal(assetPath,'/')});
test('tracked frontend names only same-origin Worker endpoint contracts',async()=>{const ui=await readFile('src/static/contest-ui.js','utf8'),app=await readFile('app.js','utf8'),cfg=await readFile('backend-config.js','utf8'),html=await readFile('index.html','utf8');for(const x of ['/api/me/registration','/api/registration','/api/public/voting'])assert.ok(ui.includes(x));for(const x of ['/api/public/competition?contest=guyun','/register','/works','/vote','/admin'])assert.ok(app.includes(x));assert.match(html,/href="\/works">作品展演/);assert.match(app,/credentials: 'same-origin'/);assert.match(app,/redirect: 'error'/);assert.match(app,/workerPath\(work\.listenUrl, \/\^\\\/api\\\/public\\\/audio/);assert.doesNotMatch(app,/mode: 'cors'|registrationApiBaseUrl|liveDataApiBaseUrl/);assert.doesNotMatch(cfg,/https?:|location\.origin/);const retiredHost=new RegExp(['ss','lip|161-33-','185-80|qin','sheng'].join(''));assert.doesNotMatch(ui+app+cfg+html,retiredHost)});
test('immutable manifest has exactly 14 ordered public-only verified files',async()=>{const m=JSON.parse(await readFile('migration/production-partial-manifest.json','utf8'));assert.equal(m.works.length,14);assert.equal(new Set(m.works.map(x=>x.filename)).size,14);assert.ok(m.works.every(x=>!('discordUserId'in x)&&!('contactEmail'in x)));assert.deepEqual([...m.works].sort((a,b)=>a.displayOrder-b.displayOrder),m.works);for(const w of m.works){const b=await readFile(path.join('media/submissions',w.filename));assert.equal(b.length,w.size);assert.equal(createHash('sha256').update(b).digest('hex'),w.sha256)}});
test('clean deterministic build preserves same-origin gallery contracts',async()=>{const out=await mkdtemp(path.join(os.tmpdir(),'moyun-build-'));const build=()=>{const x=spawnSync(process.execPath,['tools/build.mjs','--outdir',out],{encoding:'utf8'});assert.equal(x.status,0,x.stderr)};async function hashes(dir,base=dir){const result=[];for(const n of(await readdir(dir)).sort()){const p=path.join(dir,n),s=await stat(p);if(s.isDirectory())result.push(...await hashes(p,base));else result.push([path.relative(base,p).replaceAll('\\','/'),createHash('sha256').update(await readFile(p)).digest('hex')])}return result}try{build();const a=await hashes(out),html=await readFile(path.join(out,'index.html'),'utf8'),app=await readFile(path.join(out,'app.js'),'utf8'),cfg=await readFile(path.join(out,'backend-config.js'),'utf8');build();assert.deepEqual(a,await hashes(out));assert.ok(a.some(([n])=>n==='contest-ui.js'));assert.ok(!a.some(([n])=>n.startsWith('media/submissions/')));assert.match(html,/href="\/works">作品展演/);assert.match(app,/const PUBLIC_COMPETITION_PATH = '\/api\/public\/competition\?contest=guyun'/);assert.match(app,/window\.location\.assign\(WORKS_PATH\)/);assert.match(app,/workerPath\(work\.listenUrl/);assert.doesNotMatch(app+cfg,/registrationApiBaseUrl|liveDataApiBaseUrl|mode: 'cors'|window\.open\([^)]*adminUrl/)}finally{await rm(out,{recursive:true,force:true})}});
